name: Building and Testing

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 1 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    timeout-minutes: 5
    env:
      FC: gfortran-9

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Build CoSimIO
      shell: bash
      run: |
        cmake_flags="-DBUILD_C=ON -DBUILD_PYTHON=ON"
        if [ ${{ matrix.os }} != windows-latest ]; then
          cmake_flags="${cmake_flags} -DBUILD_FORTRAN=ON"
        fi
        cmake -H"." -B"build" ${cmake_flags}
        cmake --build "build" --target install

    - name: Run tests
      shell: bash
      run: |
        export PYTHONPATH=${PYTHONPATH}:${GITHUB_WORKSPACE}/bin
        cd tests
        # TODO delete build dir to make sure the linking etc works correctly?
        python run_all_tests.py
