name: Building and Testing

on:
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '0 1 * * *'

jobs:
  Unix:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]
    timeout-minutes: 5
    env:
      FC: gfortran-9

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install Valgrind
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo apt-get install valgrind

    - name: Build CoSimIO
      run: |
        cmake -H"." -B"build"  \
          -DBUILD_C=ON         \
          -DBUILD_PYTHON=ON    \
          -DBUILD_FORTRAN=OFF  \
          -DCMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS} -Werror"

        cmake --build "build" --target install

    - name: Running tests (Ctest)
      shell: bash
      run: |
        cd build
        if [ ${{ matrix.os }} == ubuntu-latest ];
          valgrind ctest --leak-check=full --show-leak-kinds=all --track-origins=yes --error-exitcode=1
        else
          ctest
        fi

    - name: Run tests
      shell: bash
      run: |
        export PYTHONPATH=${PYTHONPATH}:${GITHUB_WORKSPACE}/bin
        cd tests
        # TODO delete build dir to make sure the linking etc works correctly? (Needs to be done after running CTests)
        python run_all_tests.py


  Windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Build CoSimIO
      shell: cmd
      run: |
        call "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64 || goto :error

        set CC=cl.exe
        set CXX=cl.exe

        cmake                         ^
          -G"Visual Studio 16 2019"   ^
          -H"."                       ^
          -B"build"                   ^
          -DBUILD_C=ON                ^
          -DBUILD_PYTHON=ON           ^
          -DCMAKE_CXX_FLAGS="/WX"     || goto :error

        cmake --build "build" --target install -- /p:Platform=x64 || goto :error

        goto :EOF

        :error
        echo Failed with error #%errorlevel%.
        exit /b %errorlevel%

    - name: Running tests (Ctest)
      shell: cmd
      run: |
        set PATH=%PATH%;%GITHUB_WORKSPACE%/bin
        cd build
        ctest -C Debug

    - name: Run tests
      shell: cmd
      run: |
        set PYTHONPATH=%PYTHONPATH%;%GITHUB_WORKSPACE%/bin
        cd tests
        # TODO delete build dir to make sure the linking etc works correctly? (Needs to be done after running CTests)
        python run_all_tests.py
