name: CI

on:
  pull_request:
    branches:
      - master
  # schedule:
  #   - cron:  '0 1 * * *'

  workflow_dispatch:

concurrency:
  group: CI-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  Rocky-8:
    runs-on: ubuntu-latest
    name: Rocky 8

    container:
      image: kratosmultiphysics/kratos-image-ci-rocky8:latest
      options: --user 1001

    steps:
    - uses: actions/checkout@v4

    - name: Build CoSimIO
      run: which python3.8

