name: Mac-Profiling

on:
  push:

  workflow_dispatch:


jobs:
  MacOS-Cpp-C:
    runs-on: macOS-latest
    name: MacOS C++ & C
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v2

    - name: Build CoSimIO
      run: |
        cmake -H"." -B"build"

        cmake --build "build" --target install -- -j3

    - name: Running tests
      run: |
        export PYTHONPATH=${PYTHONPATH}:${GITHUB_WORKSPACE}/bin
        export DYLD_LIBRARY_PATH=${DYLD_LIBRARY_PATH}:${GITHUB_WORKSPACE}/bin
        ./bin/tests_cpp/export_data_cpp_test & ./bin/tests_cpp/import_data_cpp_test

        ll data_exchange_profiling/

