name: Update version after master was modified

# on:
#   push:
#     branches:
#       - 'master'

on: push
jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Patch Version
        run: |
          echo "gte hash"
          branch_name=${GITHUB_REF##*/}
          echo running on branch ${branch_name}
          
          HASH=$(git ls-remote git://github.com/KratosMultiphysics/CoSimIO.git refs/heads/${branch_name} | cut -f 1)
          echo "hash:" ${HASH}
          SHORT_HASH=$(git rev-parse --short ${HASH})
          echo "hash:" ${SHORT_HASH}
          echo "AfterHash"
          sed -i "s/DEVELOP/${SHORT_HASH}/g" co_sim_io/impl/version.hpp
          git config --global user.name 'Kratos Multiphysics Bot'
          git config --global user.email 'kratos-multiphysics-bot@users.noreply.github.com'
          # git commit -am "update patch version"
          # git push
